# Generated by Django 4.1.5 on 2023-01-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitaller', '0003_mecanico'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
