# Generated by Django 4.1.5 on 2023-01-26 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitaller', '0004_proyecto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=30)),
                ('Proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mitaller.proyecto')),
            ],
        ),
    ]
