# Generated by Django 4.1.5 on 2023-01-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitaller', '0007_cliente_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='nombremecanico',
        ),
    ]
