# Generated by Django 4.1.5 on 2023-01-26 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitaller', '0009_cliente_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='precio',
        ),
    ]
