# Generated by Django 4.1.5 on 2023-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitaller', '0011_cliente_precio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='precio',
        ),
        migrations.AddField(
            model_name='cliente',
            name='horahombre',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tarea',
            name='tiempo',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
