# Generated by Django 4.1.5 on 2023-01-28 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mitaller', '0014_remove_cliente_tarea_remove_cliente_horahombre_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarea',
            old_name='description',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='descripcion',
        ),
    ]
